### ISSUE TITLE
Your packet doesn't work in nodejs as a coffee script

### ISSUE THREAD

**Issue by gusakovm** [lteacher/simple-fxtrade#15]
Hey,
1. I added this module to my own project. So, it doesn't work: node says `Error: Cannot find module 'simple-fxtrade'.`.
2. I understood it can't works because there's no `index.js` in the module path.
3. I compilled `index.coffee` and `./lib` from coffee to js
4. It works, but I can't use it as a NPM module.

I'm not sure this is my npm issue or not (maybe I need to install some npm plugins?), but I think it doesn't work for most of people who use it.
```
#fyi 
npm -v
6.4.1
```

**Comment by lteacher** [comment]
Hi hmm I didnt get the notification for your message. I released another version not long ago but havent been using this package in a while so I might have broken that somehow... will check it

**Comment by gusakovm** [comment]
@lteacher  Thanks for the reaction, for fixes. Nice job man!

**Comment by lteacher** [comment]
Hey @gusakovm 

Per the issue details there was some problem where the `dist/` was not published. There are a few old versions of npm that had this bug and the deploy did happen from version 4.2 or so (not sure why i was basing the publish on node 7)

I did release again and the dist files are there for `node` and `browser` so the package should work again as designed.

**Comment by gusakovm** [comment]
Super
